[build]
  command = "pnpm build"
  publish = "build"

[dev]
  command = "pnpm dev"

[[redirects]]
  from = "/track/*"
  to = "/tracks/:splat"

[[redirects]]
  from = "/album/*"
  to = "/albums/:splat"
